### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by zqll4** [Quillraven/MysticWoods#3]
This project is great, do you have plans to come out with tutorials to add more features? Like the logic part of AI, I think I can make full use of the functions provided by libgdx-ai, which can make the AI logic of the game richer.

**Comment by Quillraven** [comment]
Hi,

I recently made a poll on my YT channel what else people want to see in the game and I try to make three more videos this month:
1) Light system with Box2D Light
2) map change via a portal system
3) tests / unit tests with LibGDX

Which features would you be interested in?

**Comment by zqll4** [comment]
Glad you got a reply so quickly.
Wow, all three tutorials are pretty good, and lighting and switching maps are essential parts of a complete and excellent game. I might be more interested in the testing part, though. It is an important part of development, and testing enables the rapid development of powerful and complex systems.
